config/routes.rb
Rails.application.routes.draw do
  authenticate :user do
    resources :tournaments, only: [:new, :create, :edit, :update, :destroy] do
      member do
        post :start
        post :end
      end
    end

    resources :matches, only: [:new, :create, :edit, :update, :destroy] do
      member do
        patch :validate
      end
    end

    resources :user_matches, only: [:update, :destroy]
  end

  resources :tournaments, only: [:index, :show]
  resources :matches, only: [:index, :show]
  resources :user_matches, only: [:index]
  resources :inscriptions
  get 'home/index'

  get 'home/show'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  belongs_to :officer, :class_name => 'User'
  has_many :inscriptions
  has_many :users, through: :inscriptions
  has_many :matches
  attr_accessor :general_mode

  validates_presence_of :name, :number_players, :prize, :entrance_fee, :officer_id, :date, :rounds, :mode
  validates :board_size, inclusion: {in: [4,6]}
  validates :number_players, inclusion: {in: 3..16 }
  validates :mode, inclusion: { in: -1..5}

  def start

    result = (self.mode ==-1) ? start_free4all : start_pyramidal

    if result[:status]
      self.status=1
      self.current_round = 0
      self.save
    end
    result
  end

  MODES = {(I18n.t 'tournamet_modes.free4all') => -1,
           (I18n.t 'tournamet_modes.pyramidal') => 0}

  PYRAMIDAL_MODES = {
      (I18n.t 'tournamet_modes.not_allowed') => -2,
      (I18n.t 'tournamet_modes.instantwinner') => 0,
      (I18n.t 'tournamet_modes.onewinner') => 1,
      (I18n.t 'tournamet_modes.twowinner') => 2,
      (I18n.t 'tournamet_modes.threewinner') => 3,
      (I18n.t 'tournamet_modes.fourwinner') => 4,
      (I18n.t 'tournamet_modes.fivewinner') => 5
  }

  private

  def start_free4all
    status = true
    errors = []
    selector = RoundSelector.new(self.rounds, self.users.to_a, self.board_size)
    round_matches = selector.select_all_rounds

    round_matches.each_with_index do |round, round_number|
      round.each do |match|
        user_attributes = {}
        match.each do |user|
          user_attributes[user[:id]] = {:user_id => user[:id]}
        end

        match_parameters = {
            :n_players => match.count,
            :round => round_number+1,
            :tournament_id => self.id,
            :user_matches_attributes => user_attributes
        }
        new_match = Match.new_with_child(match_parameters)
        unless new_match[:status]
          status = false
          errors.push(new_match[:errors])
          break
        end
      end

      unless status
        break
      end
    end
    {:status => status, :errors => errors}
  end

  def start_pyramidal
    status = true
    errors = []
    object = nil
    selector = PyramidGenerator.generate(self.board_size, self.mode, self.users.to_a)
    if selector[:status]
      object = selector[:object]
      all_rounds_created = []
      previous_round_ids = [nil]
      self.structure = selector[:object][:general_configuration]
      self.save
      self.reload

      keys = self.structure.keys.sort!.reverse!
      first = true

      keys.each do |key|
        current_round_ids = []
        if first or self.mode == 0
          first = false
          final_match = Match.new(
              :tournament_id => self.id,
              :round => key,
              :pyramidal_position => 0,
              :expected_number_players => self.structure[key]['matches_configuration'][0])


          if final_match.save
            current_round_ids.push(final_match.id)
          else
            status = false
            errors.push(ArgumentError.new)
            break
          end
        else
          round_conf = self.structure[key]['matches_configuration'].dup
          round_number_of_matches = self.structure[key]['number_of_matches']
          current_position = 0

          round_number_of_matches.times do |index|
            if round_conf[current_position] != 0
              round_conf[current_position] = round_conf[current_position] - self.mode
            else
              current_position = current_position + 1
            end
            if key == '0'
              user_attributes = {}
              selector[:object][:first_round][index].each do |user|
                user_attributes[user.id] = {:user_id => user.id}
              end
              match = Match.new_with_child(:tournament_id => self.id,
                                           :round => key,
                                           :pyramidal_position => index,
                                           :consumer_id => previous_round_ids[current_position],
                                           :user_matches_attributes => user_attributes)
              unless match[:status]
                status = false
                errors.push(ArgumentError.new)
              end
            else
              match = Match.new(
                  :tournament_id => self.id,
                  :round => key,
                  :pyramidal_position => index,
                  :consumer_id => previous_round_ids[current_position],
                  :expected_number_players => self.structure[key]['matches_configuration'][index])
              unless match.save
                status = false
                errors.push(ArgumentError.new)
              end
            end
          end
        end
        previous_round_ids = current_round_ids
        all_rounds_created.concat(current_round_ids)
      end

    else
      status = false
      errors = selector[:errors]
    end
    if status
      self.rounds = self.structure.count
    end
    {:status => status, :errors => errors, :object => status ? object : nil}
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :set_tournament, only: [:edit, :update, :destroy, :start]
  load_and_authorize_resource

  # GET /tournaments
  # GET /tournaments.json
  def index
    @tournaments = Tournament.all.decorate
  end

  # GET /tournaments/1
  # GET /tournaments/1.json
  def show
    @tournament = Tournament.find(params[:id]).decorate
  end

  # GET /tournaments/new
  def new
    @tournament = Tournament.new
  end

  # GET /tournaments/1/edit
  def edit
  end

  # POST /tournaments
  # POST /tournaments.json
  def create
    @tournament = Tournament.new(
        :name => tournament_params[:name],
        :number_players => tournament_params[:number_players],
        :prize => tournament_params[:prize],
        :entrance_fee => tournament_params[:entrance_fee],
        :date => tournament_params[:date],
        :board_size => tournament_params[:board_size],
        :user_id => current_user.id
    )
    if tournament_params[:general_mode]=='0'
      @tournament.rounds = tournament_params[:rounds]
      @tournament.mode = 0
    else
      @tournament.rounds = 0
      @tournament.mode = tournament_params[:mode]
    end

    respond_to do |format|
      if @tournament.save
        format.html { redirect_to @tournament, notice: ([Tournament.model_name.human, (t 'succesfully_created')].join(' ')) }
        format.json { render :show, status: :created, location: @tournament }
      else
        format.html { render :new }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tournaments/1
  # PATCH/PUT /tournaments/1.json
  def update
    respond_to do |format|
      if @tournament.update(tournament_params)
        format.html { redirect_to @tournament, notice: 'Tournament was successfully updated.' }
        format.json { render :show, status: :ok, location: @tournament }
      else
        format.html { render :edit }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tournaments/1
  # DELETE /tournaments/1.json
  def destroy
    @tournament.destroy
    respond_to do |format|
      format.html { redirect_to tournaments_url, notice: ([Tournament.model_name.human, (t 'succesfully_destroyed')].join(' ')) }
      format.json { head :no_content }
    end
  end

  def start
    status = @tournament.start
    respond_to do |format|
      if status[:status]
        format.html { redirect_to @tournament, notice: 'Tournament was successfully started.' }
        format.json { render :show, status: :created, location: @tournament }
      else
        status[:errors].each do |error|
          helpers.flash_message(:error, error)
        end
        format.html { redirect_to @tournament }
        format.json { render json: error, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tournament
      @tournament = Tournament.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tournament_params
      params.require(:tournament).permit(:name, :number_players, :prize, :entrance_fee, :user_id, :general_mode, :rounds, :date, :mode, :board_size)
    end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper

  def mode_human(mode, complete=false)
    if complete
      case mode
        when 0
          t 'tournamet_modes.free4all'
        when 1
          t 'tournamet_modes.onewinner'
        when 2
          t 'tournamet_modes.twowinner'
        when 3
          t 'tournamet_modes.threewinner'
        when 4
          t 'tournamet_modes.fourwinner'
        when 5
          t 'tournamet_modes.fivewinner'
      end
    else
      if mode ==0
        t 'tournamet_modes.free4all'
      else
        t 'tournamet_modes.pyramidal'
      end

    end

  end

end

app/views/tournaments/_edit_form.erb
<%= simple_form_for(@tournament) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :number_players, input_html: { min: '0', step: 1 }%>
      <%= f.input :prize %>
      <%= f.input :entrance_fee, input_html: { min: '0', step: 1 } %>
      <%= f.association :officer %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
<% end %>
<br>

app/views/tournaments/_max_players_fields.erb
<%= f.input :number_players, input_html: {min: 3, max: 16, step: 1}, wrapper_html: {id: 'number_players'} %>

app/views/tournaments/_pyramidal_fields.erb
<%= f.input :mode, include_blank: false, label: 'Ganadores por Partido', input_html: {title: (t 'tournamet_modes.pyramidal_tooltip'), data: {toggle: 'tooltip'}}, collection: Tournament::PYRAMIDAL_MODES, wrapper_html: {id: 'pyramidalMode'} %>

app/views/tournaments/_ranking_fields.erb
<%= f.input :rounds, input_html: {min: '1', step: 1, title: (t 'tournamet_modes.ranking_tooltip'), data: {toggle: 'tooltip'}}, wrapper_html: {id: 'rankingRounds'} %>

app/views/tournaments/_ranking_rounds.erb
<h3> <%= title %> </h3>
<% rounds.times do |round| %>
    <h4> <%= t('round') + " " + (round+1).to_s %></h4>
    <div class="row">
      <% matches.round(round+1).each_with_index do |match, index| %>
          <div class="col-md-4">
            <table class="display table table-condensed table-responsive">
              <caption>
                <%= link_to [Match.model_name.human, index+1, '-', match.status].join(' '), match %>
              </caption>
              <thead>
              <tr>
                <th><%= UserMatch.human_attribute_name(:user) %></th>
                <% if match[:validated] %>
                    <th><%= UserMatch.human_attribute_name(:vp) %></th>
                    <th><%= UserMatch.human_attribute_name(:victory_position) %></th>
                <% end %>
              </tr>
              </thead>
              <tbody>
              <% match.user_matches.each do |player| %>
                  <tr>
                    <td><%= player.user[:name] %></td>
                    <% if match[:validated] %>
                        <td><%= player[:vp] %></td>
                        <td><%= player[:victory_position] %></td>
                    <% end %>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>
      <% end %>
    </div>
<% end %>

app/views/tournaments/_register_button.erb
<div class="<%= wrapper_class %>">
  <%= simple_form_for(inscription) do |f| %>
      <%= f.input :tournament_id, as: :hidden %>
      <%= f.button(:submit_tag, (t 'register'), class: 'btn btn-success', data: {confirm: (t 'are_you_sure.base')}) %>
  <% end %>
</div>

app/views/tournaments/edit.html.erb
<h1>Editing Tournament</h1>

<%= render 'edit_form', tournament: @tournament %>

<%= link_to 'Show', @tournament %> |
<%= link_to 'Back', tournaments_path %>

app/views/tournaments/index.html.erb
<h1> <%= Tournament.model_name.human(count: 2) %> </h1>

<%= @tournaments.show_all %>


<br>

<%= link_to ([(t 'create'), Tournament.model_name.human].join(' ')), new_tournament_path, :class => 'btn btn-default' %>

app/views/tournaments/new.html.erb
<h1> <%= [(t 'new_m'), Tournament.model_name.human].join(' ') %> </h1>

<%= simple_form_for @tournament, validate: true do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">

      <%= f.input :name %>
      <%= f.input :board_size, collection: [4, 6], include_blank: false %>
      <%= f.input :general_mode, required: true, as: :radio_buttons, collection: Tournament::MODES, include_blank: false, wrapper_html: {id: 'general_mode', data: (insert_fields_data(f, 'ranking', 'ranking').merge(insert_fields_data(f, 'pyramidal', 'pyramidal')).merge(insert_fields_data(f, 'max_players', 'max_players')))} %>
      <%= f.input :prize %>
      <%= f.input :entrance_fee, input_html: {min: '0', step: 1} %>
      <%= f.input :date, as: :string, input_html: {class: 'datepicker', readonly: 'readonly', data: {minDate: Date.current}} %>
    </div>
    <div class="form-actions">
      <%= f.button :submit %>
      <%= link_to (t 'back'), tournaments_path, class: 'btn btn-danger' %>
    </div>
<% end %>
<br>

app/views/tournaments/show.html.erb
<%= @tournament.pretty_show %>

<%= @tournament.show_info %>

<div class="row">
  <%= @tournament.edit_button %>
  <%= @tournament.start_button %>
  <%= @tournament.inscription_button(current_user) %>
  <div class="col-md-1">
    <%= link_to (t 'back'), tournaments_path, class: 'btn btn-danger' %>
  </div>
</div>