config/routes.rb
Rails.application.routes.draw do
  authenticate :user do
    resources :tournaments, only: [:new, :create, :edit, :update, :destroy] do
      member do
        post :start
        post :end
      end
    end

    resources :matches, only: [:new, :create, :edit, :update, :destroy] do
      member do
        patch :validate
      end
    end

    resources :user_matches, only: [:update, :destroy]
  end

  resources :tournaments, only: [:index, :show]
  resources :matches, only: [:index, :show]
  resources :user_matches, only: [:index]
  resources :inscriptions
  get 'home/index'

  get 'home/show'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/models/match.rb
class Match < ApplicationRecord
  include ActiveModel::Validations
  has_many :user_matches, dependent: :destroy
  has_many :users, through: :user_matches
  belongs_to :tournament
  belongs_to :consumer, class_name: "Match"
  has_many :feeders, class_name: "Match", foreign_key: 'consumer_id'
  accepts_nested_attributes_for :user_matches
  validates :date, :location, client_presence: true

  scope :round, -> (round) {includes(:user_matches => :user).where(round: round)}
  scope :user, -> (user) {includes(:user_matches).where('user_matches.user_id'=>user.id)}

  def validated_human
    if self.validated
      I18n.t 'positive'
    else
      I18n.t 'negatory'
    end
  end

  def status
    self.validated ? (I18n.t :ended.F) : (I18n.t :waiting)
  end

  def validated_count
    self.user_matches.where(:validated => true).count
  end

  def user_validation
    current_user_match = @match.user_matches.find_by_user_id(current_user.id)
    success = (not current_user_match.nil?)
    if success && current_user_match.update(:validated => true)
      @match.validate_record
    end
    success
  end

  def validate_record
    if not self.validated and self.validated_count >= 2
      self.update(validated: true)

      self.set_rankings
      self.set_victory_positions

      self.user_matches.each do |user_match|
        user = user_match.user
        user_match.update(:elo_general => user.elo_general, :elo_tournament => user.elo_tournament, :elo_free => user.elo_free)
        user.increment(:matches_played)
        user.increment(:elo_general, user_match[:elo_general_change])
        user.increment(:elo_tournament, user_match[:elo_tournament_change])
        user.increment(:elo_free, user_match[:elo_free_change])

        user.save
      end
    end
  end

  def set_victory_positions
    user_matches = self.user_matches.order(vp: :desc)
    user_matches.each_with_index do |user_match, index|
      user_match.update(:victory_position => index)
    end
  end

  def set_rankings
    general = self.tournament.nil?
    tournament = (not self.tournament.nil?)

    attributes_general = []
    attributes_free = []
    attributes_tournament = []
    winner = true
    user_matches_ordered = self.user_matches.order(vp: :desc)

    user_matches_ordered.each do |elem|
      elem_user = User.find(elem[:user_id])
      general ? attributes_general.push({:rating => elem_user.elo_general, :winner => winner, :provisional => (elem_user.matches_played<=2)}) : nil
      (general or tournament) ? attributes_free.push({:rating => elem_user.elo_free, :winner => winner, :provisional => (elem_user.matches_played<=2)}) : nil
      tournament ? attributes_tournament.push({:rating => elem_user.elo_tournament, :winner => winner, :provisional => (elem_user.matches_played<=2)}) : nil
      winner = false
    end

    if general
      calculator_general = Elo_Calculator.new(attributes_general)
      ratings_general = calculator_general.calculate_rating
      ratings_general.zip user_matches_ordered.each do |rating, user_match|
        user_match.update(:elo_general_change => rating)
      end
    end

    if general or tournament
      calculator_free = Elo_Calculator.new(attributes_free)
      ratings_free = calculator_free.calculate_rating
      ratings_free.zip user_matches_ordered.each do |rating, user_match|
        user_match.update(:elo_free_change => rating)
      end
    end

    if tournament
      calculator_tournament = Elo_Calculator.new(attributes_tournament)
      ratings_tournament = calculator_tournament.calculate_rating
      ratings_tournament.zip user_matches_ordered.each do |rating, user_match|
        user_match.update(:elo_tournament_change => rating)
      end
    end
  end

  def self.new_with_child(match_params)
    #TODO rework this shit, and make tests!
    success = true
    error_list = []

    match = Match.new(
        :date => match_params[:date],
        :location => match_params[:location],
        :tournament_id => (match_params.key?(:tournament_id) ? match_params[:tournament_id] : nil),
        :consumer_id => (match_params.key?(:consumer_id) ? match_params[:consumer_id] : nil),
        :round => match_params[:round],
        :pyramidal_position => (match_params.key?(:pyramidal_position) ? match_params[:pyramidal_position] : nil),
        :expected_number_players => (match_params.key?(:expected_number_players) ? match_params[:expected_number_players] : match_params[:user_matches_attributes].count))


    n_valid = 0
    if match.save
      elems_array = []
      match_params[:user_matches_attributes].each do |_, elem|
        user_match = UserMatch.new(:user_id => elem[:user_id],
                                   :vp => elem[:vp],
                                   :match_id => match.id,
                                   :validated => elem.key?(:validated) ? elem[:validated] : false)
        n_valid = (user_match.validated ? n_valid + 1 : n_valid)

        unless user_match.save
          error_list.push(user_match.errors)
          success = false
          break
        end
        elems_array.push(user_match)
      end
    else
      error_list.push(match.errors)
      success = false
    end

    if n_valid >= 2
      match.validated = true
      unless match.save
        success = false
        error_list.push(match.errors)
      end
    end

    unless success
      match.destroy
    end
    {:status => success, :errors => error_list, :object => (success ? match : nil)}
  end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy, :validate]
  load_and_authorize_resource

  # GET /matches
  # GET /matches.json
  def index
    if current_user
      @matches = Match.includes(:users).all.decorate
    else
      @matches = Match.all.decorate
    end

  end

  # GET /matches/1
  # GET /matches/1.json
  def show
    @match = @match.decorate
    #TODO Unite @match and @users
    #@users = User.joins(:user_matches).select('users.*, user_matches.vp, user_matches.victory_position').where('user_matches.match_id' => @match.id)
  end

  # GET /matches/new
  def new
    @match = Match.new(:user_matches_attributes => {'0' => {:user_id => current_user.id}})
  end

  # GET /matches/1/edit
  def edit
    @user_matches = @match.user_matches
  end

  # POST /matches
  # POST /matches.json
  def create
    success = Match.new_with_child(match_params)
    respond_to do |format|
      if success[:state]
        format.html { redirect_to success[:object], notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        helpers.flash_message(:error, success[:errors])
        format.html { render :new }
        format.json { render json: success[:errors], status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    success = @match.update(match_params)
    if success
      @match.user_matches.each do |user_match|
        (user_match.user_id == current_user.id) ? user_match.update(:validated => true) : user_match.update(:validated => false)
      end
    end
    respond_to do |format|
      if success
        format.html { redirect_to @match, notice: t('match.validate.success') }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  def validate
    respond_to do |format|
      if @match.user_validation
        format.html { redirect_to back_or_default, notice: t('match.validate.success') }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { redirect_to back_or_default }
        format.json { render json: @user_match.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_match
    @match = Match.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def match_params
    params.require(:match).permit(:n_players, :round, :pyramidal_position, :date, :location, user_matches_attributes: [:id, :user_id, :validated, :vp, :_destroy])
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= simple_form_for @match, validate: true do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :date, as: :string, input_html: {class: 'datepicker', readonly: 'readonly', data: {minDate: Date.current}} %>
      <%= f.input :location %>
      <div class="row">
          <%= f.simple_fields_for :user_matches do |m| %>
            <div class="col-md-3">
              <%= m.association :user, :disabled => true, input_html: {data: {max_users: User.all.count, error_message: (t 'activerecord.errors.models.match.attributes.n_players.inclusion')}} %>
            </div>

            <div class="col-md-2">
              <%= m.input :vp, as: :integer, input_html: {min: 1, step: 1, max: 10, value: 1} %>
            </div>
            <%= m.hidden_field :user_id %>
            <%= m.hidden_field :validated, value: true %>
          <% end %>
      </div>

      <%= link_to_add_fields 'Agregar Jugador', f, :user_matches, true, 'add_purchase_item' %>
    </div>
    <br>

    <div class="form-actions">
      <%= f.button :submit, id: 'submit_button' %>
      <%= link_to (t 'back'), matches_path, class: 'btn btn-danger' %>
    </div>
<% end %>

app/views/matches/_players.erb
<h3>Jugadores</h3>
<table class="display table table-condensed table-responsive">
  <thead>
  <tr>
    <th><%= User.human_attribute_name(:name) %> </th>
    <th><%= UserMatch.human_attribute_name(:victory_position) %></th>
    <th class="center_element"><%= UserMatch.human_attribute_name(:vp) %></th>
    <th class="center_element"><%= User.human_attribute_name(:position_general) %></th>
    <th class="center_element"><%= User.human_attribute_name(:position_tournament) %></th>
    <th class="center_element"><%= User.human_attribute_name(:position_free) %></th>
    <th class="center_element"><%= User.human_attribute_name(:matches_played) %></th>
  </tr>
  </thead>
  <tbody>
  <% user_matches.each do |r| %>
      <tr>
        <td><%= r.name %></td>
        <td align="center"><%= r.victory_position%></td>
        <td align="center"><%= r.vp %></td>
        <td align="center"><%= r.position_general %></td>
        <td align="center"><%= r.position_tournament %></td>
        <td align="center"><%= r.position_free %></td>
        <td align="center"><%= r.matches_played %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/matches/_test_form.erb
<%= simple_form_for @match, validate: true do |f| %>
    <%= f.error_notification %>

    <%= content_tag :div, :class => 'form-inputs', :id => 'inputs', data: {
        not_tournament: true,
        current_users: 1,
        max_users: User.all.count,
        error_message: (t 'activerecord.errors.models.match.attributes.n_players.inclusion')} do %>

        <%= f.input :date, as: :string, validate: {presence: true}, input_html: {class: 'datepicker', readonly: 'readonly', data: {minDate: Date.current}} %>
        <%= f.input :location, validate: {presence: true} %>
        <div class="row">
          <%= f.simple_fields_for :user_matches do |m| %>
              <div class="col-md-3">
                <%= m.association :user, :disabled => true, input_html: {data: {max_users: User.all.count, error_message: (t 'activerecord.errors.models.match.attributes.n_players.inclusion')}} %>
              </div>

              <div class="col-md-2">
                <%= m.input :vp, as: :integer, input_html: {min: 1, step: 1, max: 10, value: 1} %>
              </div>


              <%= m.hidden_field :user_id %>
              <%= m.hidden_field :validated, value: true %>
          <% end %>
        </div>

        <%= link_to_add_fields 'Agregar Jugador', f, :user_matches, true, 'add_purchase_item' %>
    <% end %>
    <br>

    <div class="form-actions">
      <%= f.button :submit, id: 'submit_button' %>
      <%= link_to (t 'back'), matches_path, class: 'btn btn-danger' %>
    </div>
<% end %>

app/views/matches/_user_match_fields.erb
<fieldset>
  <div class="form-inputs row">
    <div class="col-md-3">
      <%= f.association :user, include_blank: false %>
    </div>

    <div class="col-md-2">
      <%= f.input :vp, input_html: {min: 1, step: 1, max: 10, value: 1} %>
    </div>

    <div class="col-md-1 ">
      <%= f.hidden_field :_destroy %>
      <%= link_to '#', class: 'btn btn-default remove_fields', :style => 'margin-top: 25px; margin-left: 0px' do %>
          <i class="glyphicon glyphicon-remove"></i>
      <% end %>
    </div>
  </div>
</fieldset>

app/views/matches/edit.html.erb
<h1>Editing Match</h1>

<%= simple_form_for @match, validate: true do |f| %>
    <%= f.error_notification %>
    <%= content_tag :div, :class => 'form-inputs', :id => 'inputs', data:
        {not_tournament: @match.tournament_id.nil?,
         current_users: @match.user_matches.count,
         max_users: User.all.count,
         error_message: (t 'activerecord.errors.models.match.attributes.n_players.inclusion')} do %>

        <%= f.input :date, as: :string, validate: {presence: true}, input_html: {class: 'datepicker', readonly: 'readonly', data: {minDate: Date.current}} %>
        <%= f.input :location, validate: {presence: true}, allow_blank: false %>

        <%= f.simple_fields_for :user_matches do |m| %>
            <div class="row">
              <div class="col-md-3">
                <%= m.association :user, :disabled => true %>
              </div>
              <div class="col-md-2">
                <%= m.input :vp, as: :integer, validate: {presence: true}, input_html: {min: 1, step: 1, max: 10} %>
                <%= m.input :id, as: :hidden %>
              </div>
            </div>
        <% end %>


        <%= link_to_add_fields 'Agregar Jugador', f, :user_matches, true, 'add_purchase_item' %>
    <% end %>
    <br>

    <div class="form-actions">
      <%= f.button :submit, id: 'submit_button' %>
      <%= link_to (t 'back'), matches_path, class: 'btn btn-danger' %>
    </div>
<% end %>

app/views/matches/index.html.erb
<%= @matches.show_user_matches %>
<br>
<h2><%= t 'all_matches' %></h2>
<%= @matches.show_all %>

<br>

<%= link_to ([(t 'create'), Match.model_name.human].join(' ')), new_match_path, :class => 'btn btn-default' %>

app/views/matches/new.html.erb
<h1> <%= [(t 'new_f'), Match.model_name.human].join(' ') %> </h1>

<%= render 'form', match: @match %>

app/views/matches/show.html.erb
<%= @match.pretty_show %>

<%= @match.show_players %>



<div class="row">
  <% if can? :update, @match %>
      <div class="col-md-1">
        <%= link_to (t 'edit'), edit_match_path(@match), class: 'btn btn-info' %>
      </div>
  <% end %>
  <% if can? :validate, @match %>
      <div class="col-md-2 center-block">
        <%= simple_form_for @match, url: validate_match_path(@match), method: :patch do |f| %>
            <%= f.button :submit_tag, (t 'validate'), :class => 'btn btn-success' %>
        <% end %>
      </div>
  <% end %>
  <div class="col-md-1">
    <%= link_to (t 'back'), back_or_default(matches_path), class: 'btn btn-danger' %>
  </div>


</div>