config/routes.rb
Rails.application.routes.draw do
  authenticate :user do
    resources :tournaments, only: [:new, :create, :edit, :update, :destroy] do
      member do
        post :start
        post :end
      end
    end

    resources :matches, only: [:new, :create, :edit, :update, :destroy] do
      member do
        patch :validate
      end
    end

    resources :user_matches, only: [:update, :destroy]
  end

  resources :tournaments, only: [:index, :show]
  resources :matches, only: [:index, :show]
  resources :user_matches, only: [:index]
  resources :inscriptions
  get 'home/index'

  get 'home/show'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/views/layouts/_flash_message.erb
<div class="container alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
  <% if type == 'error' && message.is_a?(Array) %>
    <p><%= message[0] %></p>
    <ul>
        <% message[1].each do |p| %>
        <li><%= p.second.first %></li>
        <% end %>
    </ul>
    <% else %>
    <p><%= message %></p>
    <% end %>

</div>

app/views/layouts/_general_show.erb
<table class="<%= table_class %>">
  <thead>
  <tr>
    <th><h3>Datos del Torneo</h3></th>
  </tr>

  </thead>
  <tbody>
  <% @tournament.presentable_attributes.each do |attribute_name| %>
      <tr>
        <td> <%= Tournament.human_attribute_name(attribute_name) %> </td>
        <td> <%= @tournament.send(attribute_name) %> </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Catan Leaderboards</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body data-locale="<%= I18n.locale %>"  >
  <%= nav_bar brand: 'Ranking Catan', brand_link: root_path, responsive: true, inverse: false do %>

      <% if user_signed_in? %>
          <%= menu_group pull: :left do %>
              <%= menu_item (Tournament.model_name.human(count: 2)), tournaments_path, turbolinks: false %>
              <%= menu_item (Match.model_name.human(count: 2)), matches_path, turbolinks: false %>
          <% end %>

        <%= menu_group pull: :right do %>
              <%= menu_item ([(t 'logged_in'), '<strong>', current_user.email, '</strong>'].join(' ')).html_safe, edit_user_registration_path %>
          <%= menu_item (t :sign_out), destroy_user_session_path, method: :delete %>
        <% end %>
      <% else %>
          <%= simple_form_for(:user, :url => session_path(:user), :html => {:class => 'navbar-form pull-right'}) do |f| %>
              <%= f.input :email, as: :email, label: false, placeholder: 'Usuario' %>
              <%= f.input :password, as: :password, label: false, placeholder: 'Contraseña' %>
              <%= f.input :remember_me, as: :boolean, inline_label: '¿Recordarme?' %>
              <%= f.button :submit %>
              <%= link_to (t :sign_up), new_registration_path(:user) %>
          <% end %>
      <% end %>


    <% end %>

    <%= render_flash %>

    <div class="container">
      <%= yield %>
      <br><br>
    </div>

  </body>
</html>